[project]
name = "mcp-chinookdb-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno[mcp]>=1.5.1",
    "httpx>=0.28.1",
    "mcp>=1.9.0",
    "openai>=1.79.0",
]
